### ISSUE TITLE
Hi! Do you have the SQL for the Structure?

### ISSUE THREAD

**Issue by marquesmatheus** [vamshimorlawar/QuizPlatform#1]
Hi thx for share the project, do u have the credentials or the .sql for tables structures?

**Comment by vamshimorlawar** [comment]
> Hi thx for share the project, do u have the credentials or the .sql for tables structures?

I will add it by today. Thanks

**Comment by vamshimorlawar** [comment]
> Hi thx for share the project, do u have the credentials or the .sql for tables structures?

Hey, I have uploaded the .sql file. Hope this helps you.
I am closing this issue.
